### PR TITLE
Replace hardcoded path returned for node binary

### PR DESCRIPTION
**Pull request by amitsadaphule**
Incorporates the review comment: https://github.com/leo-lb/electron/pull/3#discussion_r463583272

### CODE REVIEW

**Comment by llebout** [comment]
Awesome thanks! Note, I never needed modifying that patch and I never installed nodejs as system. Weird. Merging anyway, I assume you went this far because you tested. 

You will also need to update the submodule in the electron fork, by doing "git pull" when in the chromium_power subdirectory and pushing.

**Comment by amitsadaphule** [comment]
Thanks @leo-lb! Yes, I tested the change.

About the submodule update, I thought https://github.com/amitsadaphule/electron/blob/7-2-x/.gitmodules#L10 and https://github.com/amitsadaphule/electron/blob/7-2-x/DEPS#L23 + https://github.com/amitsadaphule/electron/blob/7-2-x/DEPS#L105 already take care of that. That's how I had tested this, by pushing to https://github.com/amitsadaphule/electron/commits/7-2-x_nonabs.

Am I missing something here?

**Comment by llebout** [comment]
@amitsadaphule Not sure, at least, the repo itself keeps submodule metadata beyond just the branch, see here: https://github.com/leo-lb/electron/tree/7-2-x/patches/ppc64le - I'll push to update the submodule and merge it all, thanks a lot :-)

**Comment by amitsadaphule** [comment]
Thanks @leo-lb! It may be used while manually cloning and fetching submodules. It seems that "gclient sync .." does not consider it. Thanks for catching that and updating the submodule. :-)

**Pull request merged**
